In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

### Arrays and Matrices

In [23]:
# Array
studentdata = np.array([ ["Name", "Year", "Marks"], 
               ["Bela", 2014, 78.2],
                ["Joe", 1987, 59.1],
               ["Sugar", 1990, 70]])
#print(studentdata.shape)
print(studentdata[:,0])

['Name' 'Bela' 'Joe' 'Sugar']


In [6]:
# for memory management
c = np.array([[1,2,3,4], [5,6,7,8]],dtype='int8')
print(np.size(c))
print(np.shape(c))

8
(2, 4)


In [4]:
# Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. 
# Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.
b = np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [ ]:
# Special Matrices
O = np.ones((4,4))
Z = np.zeros((3,3))
I = np.identity(4)

In [ ]:
# Algebra
np.dot(a,a)            # equals to a@a
np.prod(a)             # multiplying all of the elements
np.sum(a)              # Summation
np.cumsum(a,axis=0)
np.subtract(a,a)       # Subtraction
np.divide([3,5,6],2)   # Division
np.floor_divide([3,5,6],2)

### Ranges

In [4]:
# arange
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [5]:
# linspace
# linspace(start, stop, num=50, endpoint=True, retstep=False)
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [24]:
# An example
A2 = np.arange(50).reshape(5,10)

### Math

In [26]:
np.math.sqrt(16)

4.0

In [27]:
n = np.math.nan
m = np.math.inf

inf

### Polynomial

In [34]:
coeff = [1,1,2] # x^2 + x + 2
np.polyval(coeff,1)

4

In [35]:
np.polyder(coeff)

array([2, 1])

In [36]:
np.polyint(coeff)

array([0.33333333, 0.5       , 2.        , 0.        ])

### Statistic

In [33]:
data = [1,2,3,4,5]
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

3.0
3.0
1.4142135623730951
2.0


### Generating Random Numbers

In [28]:
np.random.uniform(1,5,(2,3))

array([[3.87090803, 3.29290939, 3.52200606],
       [3.72458333, 4.58694664, 4.03232661]])

In [29]:
np.random.standard_normal((2,3))

array([[-0.73666713,  0.08867472,  0.69056089],
       [-1.37993512, -0.98981307, -2.63002743]])